### ISSUE TITLE
why there is a MongoDB connection string and how to change the Postreqsql connection

### ISSUE THREAD

**Issue by Hesat-r** [SergPerep/tasklist#1]
Hey i would like to test the project and work with it but when i installed all on the node modules on the tasklist site there was written:

info: server started on port 5000 {"timestamp":"2022-03-05 14:50:33"}
Error: Error connecting to db: bad auth : Authentication failed.
    at C:\Users\hesat\Desktop\tasklist\node_modules\connect-mongodb-session\index.js:88:17
    at C:\Users\hesat\Desktop\tasklist\node_modules\mongodb\lib\utils.js:500:17
    at C:\Users\hesat\Desktop\tasklist\node_modules\mongodb\lib\mongo_client.js:129:28
    at connectCallback (C:\Users\hesat\Desktop\tasklist\node_modules\mongodb\lib\operations\connect.js:29:9)
    at C:\Users\hesat\Desktop\tasklist\node_modules\mongodb\lib\operations\connect.js:78:20
    at C:\Users\hesat\Desktop\tasklist\node_modules\mongodb\lib\sdam\topology.js:212:58
    at C:\Users\hesat\Desktop\tasklist\node_modules\mongodb\lib\cmap\connection_pool.js:270:25
    at C:\Users\hesat\Desktop\tasklist\node_modules\mongodb\lib\sdam\server.js:187:24
    at Object.callback (C:\Users\hesat\Desktop\tasklist\node_modules\mongodb\lib\cmap\connection_pool.js:267:13)
    at C:\Users\hesat\Desktop\tasklist\node_modules\mongodb\lib\cmap\connection_pool.js:475:29

then i found the password from the repositories from before and added the password but the screen was white so i found die client folder and also started it from there and installed all repos this was the error when i was trying to register

Proxy error: Could not proxy request /auth/register from localhost:3000 to http://localhost:5000/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).

could you give a step by step tutorial to set up the projekt ? because there was also a branch with the database do i need it ? 
or what should i start or change to get the project work, i also didnt finde the file to change the postreqsql creditinals

i would realy preciate it if you would write how to install the project corectly change the database informations , why  there is a mongo db connection and how to start the project correctly

**Comment by SergPerep** [comment]
Hi @Hesat-r,
Quick answers:

**Why there is a MongoDB connection string?**
I use MongoDB to store user sessions that enable a use of user accounts. That way each user of my app can have their own tasks and projects. Connection string is requied to connect to MongoDB. If you want to set up this project in your local machine, you need to create account on MongoDB and configure your own database and connection parameters. It means your own mongoDB `<username>`, `<password>`, `<cluster-name>` and `<db-name>`. [Article by freecodecamp](https://www.freecodecamp.org/news/get-started-with-mongodb-atlas/) can help you with that.

**Proxy error**
I don't think that I can help you with this. Maybe you'll resolve it by fixing connection to databases.

**There was also a branch with the database do i need it?**
You need only master-branch. Database-branch is useless for you.

**I also didn't find the file to change the postreSQL credentials**
Parameters of connections to databases stored inside `.env` file. Because it holds secret information, it is not pushed to repository: it is added to [.gitignore](https://github.com/SergPerep/tasklist/blob/master/.gitignore). You should create one of your own in root directory.

**Comment by SergPerep** [comment]
@Hesat-r,
Regarding step-by-step installation, here is [simple a guide](https://github.com/SergPerep/tasklist/blob/master/setup/setup-guide.md) for you.
Keep in mind, that this project is work-in-progress, and a lot can be changed or work differently in near future.

**Comment by Hesat-r** [comment]
hey @SergPerep 

thank you for you fast response because of your fast help and the setup.md tutorial i now can use the project. Thank you for you good work keep going
